### ISSUE TITLE
Question about mAP

### ISSUE THREAD

**Issue by 1991viet** [imatge-upc/retrieval-2017-cam#3]
Hi authors,
    I have a question regarding the mAP on your model.
    In your paper, the table 2 shows a comparison between your model (onl and off) and other ones. So my question is, the result showed here are mAP when you included 55 query images on the training phase or not.
    Specifically, take the Oxford5k as an example. After we run the script **A_Oxf_Par_Feat_CAMs_Extraction.py** (offine version), we could have output desc_wp with shape of **[5063,512]** if we include 55 images from query images (and this is the default setting on your code), or if I comment the part for extracting feature and CAM for query images, we will have the output desc_wp with shape of **[5008,512]**. Then we run the same script one more time for Paris6k dataset, which will be used for PCA for Oxford5k later on. Then we could run the script **B_Offine_eval.py** for Oxford5k dataset. In case I included query images when running the script A_Oxf_Par_Feat_CAMs_Extraction.py (output.shape = [5063,512]), the mAPs I have after running the script B_Offine_eval.py is very close to the results on your paper. For example, with offine version, dim = 512, R = 100, QE = 10, for the oxford5k dataset, you reported mAP of 0.773, my result is 0.778. Or for the Paris dataset, you reported mAP of 0.838, my result is 0.849. But if I do not include 55 query images when running the script A_Oxf_Par_Feat_CAMs_Extraction.py (output.shape = [5008,512]), the mAP I have after running B_Offine_eval.py drop significantly (as I remember for Oxford5k, my mAP is less than 0.4). I hope that I do not do anything wrong here.
    I read other paper like CroW, BoW or RMAC, but authors do not explicitly state that whether they include query image when training or not. So I wonder, which is the standard setting in Image Retrieval field ? include or not include test images in training phase ?

**Comment by jsalbert** [comment]
We computed the PCA matrix with all the images of Oxf5k dataset to apply the transform on the Paris descriptors and vice versa. To compute the PCA I don't think 55 images have a strong significance. I think that you are getting less accuracy because the query images have to be included in the test dataset, even the query, as is the standard way of evaluating these 2 datasets.

**Comment by 1991viet** [comment]
Thank you for your answer. It makes sense :)

**Comment by jsalbert** [comment]
No worries, happy to help!
