### ISSUE TITLE
About the parameter N_PCA

### ISSUE THREAD

**Issue by qiulesun** [imatge-upc/retrieval-2017-cam#4]
I do not understand the parameter N_PCA in Section 4.3, such as its use, and why it is introduced. I am looking forward to your reply.

**Comment by jsalbert** [comment]
Hi @TensorDL, 

Our descriptors are computed by weighing and summing features. We use `N_c` referring to the number of classes or CAMs that we use to compute the descriptors. 
PCA is introduced in these datasets as a way of domain transfer from Imagenet --> Oxford/Paris. 
PCA is computed on top of our descriptors. So `N_pca` is the number of classes we have used to aggregate the descriptors for the PCA computation.  
It does not need to be the same as `N_c` and we showed different experiments showing the effects of varying that parameter.

**Comment by qiulesun** [comment]
So, what is the difference between N_c and N_pca?

**Comment by jsalbert** [comment]
`N_c` is the number of classes used to compute the descriptors and `N_Pca` is the number of classes used to compute the descriptors just for the PCA. 

PCA is computed with the descriptors of Paris if we are testing with Oxford and viceversa. So you could choose computing the PCA with the Paris descriptors using `N_pca=1 class` and then aggregate the Oxford descriptors using `N_c=6 classes` for example. 

The dimensions of the final vector are independent of the number of classes used to aggregate it. 

We wanted to see the effects of this param.

**Comment by qiulesun** [comment]
Thank you for your reply. But I still have some confusion about the classes for the PCA computation. In mean the classes from Oxford/Paris?

**Comment by jsalbert** [comment]
The classes are from ImageNet.

To compute descriptors for Oxford the process is as follows:

- Paris dataset --> Extract features --> Compute descriptors with `N_PCA` top-classes --> Compute PCA matrix (`Pca_matrix_paris`)

- Oxford dataset --> Extract features --> Compute descriptors with `N_c` top-classes --> Apply PCA matrix transform with  `Pca_matrix_paris` --> Oxford descriptors

Top-classes mean for each image the top number of imagenet classes predicted by the network.

**Comment by qiulesun** [comment]
The answer is clear, and I understand the parameters N_pca and N_c. Thank you very much!
