### ISSUE TITLE
what is the speed of feature extraction

### ISSUE THREAD

**Issue by neouyghur** [imatge-upc/retrieval-2017-cam#6]
Hi, I am trying to extract features for 1 million images. However, it is too slow. I have to wait for at least four days even I tried the fast version.  What is the speed of yours?

Plus is this warning related to the speed? should I fix it for speeding up?
`WARNING (theano.tensor.blas): We did not find a dynamic library in the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.
`
Thanks.

**Comment by neouyghur** [comment]
Hi, I solved the problem. I found out Theano is not using the GPU.  It would be better you can offer keras with Tensorflow backend. Thanks.

**Comment by jsalbert** [comment]
Happy to see you solved your problem. Unfortunately, I have no longer time to support this project.
