### ISSUE TITLE
Problem when getting the features

### ISSUE THREAD

**Issue by WendyDong** [imatge-upc/retrieval-2017-cam#9]
when I run the A_Oxf_Par_Feat_CAMs_Extraction.py script. there was a bug
 ```Input dimension mis-match. (input[0].shape[1] = 3, input[1].shape[1] = 64)```
which looks like hapeen in the conv_1 layer. Details are as follows.

![image](https://user-images.githubusercontent.com/29163870/48684604-64758500-ebed-11e8-8308-d43760725768.png)

Thanks a lot!

**Comment by uiui816** [comment]
hello.Do you solve you problem?I also have a problem when I run the A_Oxf_Par_Feat_CAMs_Extraction.py script.And I have no idea to do . the message I got is:

Default dataset:  Oxford
Default aggregation:  Offline
Traceback (most recent call last):
  File "/home/bbzhang/packforpy2cam/test/retrieval-cam/keras_code/A_Oxf_Par_Feat_CAMs_Extraction.py", line 71, in <module>
    model = vggcam(nb_classes)
  File "/home/bbzhang/packforpy2cam/test/retrieval-cam/keras_code/vgg_cam.py", line 31, in vggcam
    model.add(Convolution2D(64, 3, 3, activation='relu'))
  File "/home/bbzhang/.virtualenvs/py2cam/local/lib/python2.7/site-packages/keras/models.py", line 308, in add
    output_tensor = layer(self.outputs[0])
  File "/home/bbzhang/.virtualenvs/py2cam/local/lib/python2.7/site-packages/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])
  File "/home/bbzhang/.virtualenvs/py2cam/local/lib/python2.7/site-packages/keras/layers/convolutional.py", line 410, in build
    self.W = self.init(self.W_shape, name='{}_W'.format(self.name))
  File "/home/bbzhang/.virtualenvs/py2cam/local/lib/python2.7/site-packages/keras/initializations.py", line 57, in glorot_uniform
    fan_in, fan_out = get_fans(shape, dim_ordering=dim_ordering)
  File "/home/bbzhang/.virtualenvs/py2cam/local/lib/python2.7/site-packages/keras/initializations.py", line 15, in get_fans
    receptive_field_size = np.prod(shape[2:])
  File "/home/bbzhang/.virtualenvs/py2cam/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2539, in prod
    out=out, **kwargs)
  File "/home/bbzhang/.virtualenvs/py2cam/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 35, in _prod
    return umr_prod(a, axis, dtype, out, keepdims)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

thank you for you help

**Comment by Thyme03** [comment]
Do you solve your problem? I have exactly the same.

**Comment by aiyanxiao** [comment]
I also meet the same problem as yours, could you help me with it?  Thanks very much!

**Comment by aiyanxiao** [comment]
> hello.Do you solve you problem?I also have a problem when I run the A_Oxf_Par_Feat_CAMs_Extraction.py script.And I have no idea to do . the message I got is:
> 
> Default dataset: Oxford
> Default aggregation: Offline
> Traceback (most recent call last):
> File "/home/bbzhang/packforpy2cam/test/retrieval-cam/keras_code/A_Oxf_Par_Feat_CAMs_Extraction.py", line 71, in
> model = vggcam(nb_classes)
> File "/home/bbzhang/packforpy2cam/test/retrieval-cam/keras_code/vgg_cam.py", line 31, in vggcam
> model.add(Convolution2D(64, 3, 3, activation='relu'))
> File "/home/bbzhang/.virtualenvs/py2cam/local/lib/python2.7/site-packages/keras/models.py", line 308, in add
> output_tensor = layer(self.outputs[0])
> File "/home/bbzhang/.virtualenvs/py2cam/local/lib/python2.7/site-packages/keras/engine/topology.py", line 487, in **call**
> self.build(input_shapes[0])
> File "/home/bbzhang/.virtualenvs/py2cam/local/lib/python2.7/site-packages/keras/layers/convolutional.py", line 410, in build
> self.W = self.init(self.W_shape, name='{}_W'.format(self.name))
> File "/home/bbzhang/.virtualenvs/py2cam/local/lib/python2.7/site-packages/keras/initializations.py", line 57, in glorot_uniform
> fan_in, fan_out = get_fans(shape, dim_ordering=dim_ordering)
> File "/home/bbzhang/.virtualenvs/py2cam/local/lib/python2.7/site-packages/keras/initializations.py", line 15, in get_fans
> receptive_field_size = np.prod(shape[2:])
> File "/home/bbzhang/.virtualenvs/py2cam/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2539, in prod
> out=out, **kwargs)
> File "/home/bbzhang/.virtualenvs/py2cam/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 35, in _prod
> return umr_prod(a, axis, dtype, out, keepdims)
> TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
> 
> thank you for you help

I also meet the same problem as yours, could you help me with it? Thanks very much!
